# Generated by Django 3.1.7 on 2023-04-18 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='star_rating',
            field=models.IntegerField(default=0),
        ),
    ]
