# Generated by Django 3.1.7 on 2023-04-19 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20230418_2321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='input_data',
            new_name='input',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='output_data',
            new_name='output',
        ),
    ]
