# Generated by Django 3.1.7 on 2023-04-20 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20230419_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='image_data',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
